[2024-02-04T15:28:06.595+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: modeling_dag.load_modeling scheduled__2024-02-04T15:27:00+00:00 [queued]>
[2024-02-04T15:28:06.602+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: modeling_dag.load_modeling scheduled__2024-02-04T15:27:00+00:00 [queued]>
[2024-02-04T15:28:06.602+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-02-04T15:28:06.615+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_modeling> on 2024-02-04 15:27:00+00:00
[2024-02-04T15:28:06.621+0000] {standard_task_runner.py:57} INFO - Started process 269 to run task
[2024-02-04T15:28:06.624+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'modeling_dag', 'load_modeling', 'scheduled__2024-02-04T15:27:00+00:00', '--job-id', '1022', '--raw', '--subdir', 'DAGS_FOLDER/modeling.py', '--cfg-path', '/tmp/tmpdllan3dn']
[2024-02-04T15:28:06.626+0000] {standard_task_runner.py:85} INFO - Job 1022: Subtask load_modeling
[2024-02-04T15:28:06.664+0000] {task_command.py:410} INFO - Running <TaskInstance: modeling_dag.load_modeling scheduled__2024-02-04T15:27:00+00:00 [running]> on host 93456042b127
[2024-02-04T15:28:06.734+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='modeling_dag' AIRFLOW_CTX_TASK_ID='load_modeling' AIRFLOW_CTX_EXECUTION_DATE='2024-02-04T15:27:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-04T15:27:00+00:00'
[2024-02-04T15:28:07.486+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"

[2024-02-04T15:28:07.513+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  "X does not have valid feature names, but"

[2024-02-04T15:28:07.639+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but ExtraTreesRegressor was fitted with feature names
  "X does not have valid feature names, but"

[2024-02-04T15:28:07.650+0000] {python.py:183} INFO - Done. Returned value was: (array([35.54584817]), array([3]))
[2024-02-04T15:28:07.673+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=modeling_dag, task_id=load_modeling, execution_date=20240204T152700, start_date=20240204T152806, end_date=20240204T152807
[2024-02-04T15:28:07.719+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-02-04T15:28:07.738+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
