[2023-10-20T15:42:05.477+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: combined_dag.predict_ntu_task scheduled__2023-10-20T15:41:00+00:00 [queued]>
[2023-10-20T15:42:05.483+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: combined_dag.predict_ntu_task scheduled__2023-10-20T15:41:00+00:00 [queued]>
[2023-10-20T15:42:05.483+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-10-20T15:42:05.494+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): predict_ntu_task> on 2023-10-20 15:41:00+00:00
[2023-10-20T15:42:05.501+0000] {standard_task_runner.py:57} INFO - Started process 2674 to run task
[2023-10-20T15:42:05.504+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'combined_dag', 'predict_ntu_task', 'scheduled__2023-10-20T15:41:00+00:00', '--job-id', '382', '--raw', '--subdir', 'DAGS_FOLDER/combined_dag(real).py', '--cfg-path', '/tmp/tmpssd5l7er']
[2023-10-20T15:42:05.504+0000] {standard_task_runner.py:85} INFO - Job 382: Subtask predict_ntu_task
[2023-10-20T15:42:05.538+0000] {task_command.py:410} INFO - Running <TaskInstance: combined_dag.predict_ntu_task scheduled__2023-10-20T15:41:00+00:00 [running]> on host 310b365e0fea
[2023-10-20T15:42:05.605+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='combined_dag' AIRFLOW_CTX_TASK_ID='predict_ntu_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-20T15:41:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-20T15:41:00+00:00'
[2023-10-20T15:42:05.615+0000] {logging_mixin.py:150} INFO - [[1.810908], [1.8453709999999999], [1.8375]]
[2023-10-20T15:42:05.615+0000] {combined_dag(real).py:58} INFO - [[1.810908], [1.8453709999999999], [1.8375]]
[2023-10-20T15:42:06.276+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  "X does not have valid feature names, but"

[2023-10-20T15:42:06.946+0000] {logging_mixin.py:150} INFO - 1/1 [==============================] - ETA: 0s
[2023-10-20T15:42:06.946+0000] {logging_mixin.py:150} INFO - 1/1 [==============================] - 1s 614ms/step
[2023-10-20T15:42:06.948+0000] {logging_mixin.py:150} INFO - new data : [[1.810908], [1.8453709999999999], [1.8375]]
[2023-10-20T15:42:06.948+0000] {logging_mixin.py:150} INFO - t+1 ntu : [1.0351591]
[2023-10-20T15:42:06.948+0000] {logging_mixin.py:150} INFO - <class 'numpy.ndarray'>
[2023-10-20T15:42:06.948+0000] {python.py:183} INFO - Done. Returned value was: [1.0351591]
[2023-10-20T15:42:06.966+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=combined_dag, task_id=predict_ntu_task, execution_date=20231020T154100, start_date=20231020T154205, end_date=20231020T154206
[2023-10-20T15:42:07.018+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-10-20T15:42:07.038+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
