[2023-10-20T14:39:24.219+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: combined_dag.load_modeling manual__2023-10-20T14:39:18.324036+00:00 [queued]>
[2023-10-20T14:39:24.226+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: combined_dag.load_modeling manual__2023-10-20T14:39:18.324036+00:00 [queued]>
[2023-10-20T14:39:24.226+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-10-20T14:39:24.235+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_modeling> on 2023-10-20 14:39:18.324036+00:00
[2023-10-20T14:39:24.242+0000] {standard_task_runner.py:57} INFO - Started process 1465 to run task
[2023-10-20T14:39:24.244+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'combined_dag', 'load_modeling', 'manual__2023-10-20T14:39:18.324036+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/combined_dag(real).py', '--cfg-path', '/tmp/tmpfib_y676']
[2023-10-20T14:39:24.245+0000] {standard_task_runner.py:85} INFO - Job 124: Subtask load_modeling
[2023-10-20T14:39:24.276+0000] {task_command.py:410} INFO - Running <TaskInstance: combined_dag.load_modeling manual__2023-10-20T14:39:18.324036+00:00 [running]> on host bea49855d648
[2023-10-20T14:39:24.331+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='combined_dag' AIRFLOW_CTX_TASK_ID='load_modeling' AIRFLOW_CTX_EXECUTION_DATE='2023-10-20T14:39:18.324036+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-20T14:39:18.324036+00:00'
[2023-10-20T14:39:25.064+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"

[2023-10-20T14:39:25.113+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  "X does not have valid feature names, but"

[2023-10-20T14:39:25.386+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but ExtraTreesRegressor was fitted with feature names
  "X does not have valid feature names, but"

[2023-10-20T14:39:25.401+0000] {python.py:183} INFO - Done. Returned value was: (array([38.75854709]), array([2]))
[2023-10-20T14:39:25.421+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=combined_dag, task_id=load_modeling, execution_date=20231020T143918, start_date=20231020T143924, end_date=20231020T143925
[2023-10-20T14:39:25.459+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-10-20T14:39:25.476+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
