[2023-12-18T13:49:57.679+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: combined_dag.load_modeling scheduled__2023-12-18T13:48:00+00:00 [queued]>
[2023-12-18T13:49:57.686+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: combined_dag.load_modeling scheduled__2023-12-18T13:48:00+00:00 [queued]>
[2023-12-18T13:49:57.687+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-12-18T13:49:57.696+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_modeling> on 2023-12-18 13:48:00+00:00
[2023-12-18T13:49:57.702+0000] {standard_task_runner.py:57} INFO - Started process 269 to run task
[2023-12-18T13:49:57.705+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'combined_dag', 'load_modeling', 'scheduled__2023-12-18T13:48:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/combined_dag(real).py', '--cfg-path', '/tmp/tmpwdqmdh25']
[2023-12-18T13:49:57.707+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask load_modeling
[2023-12-18T13:49:57.741+0000] {task_command.py:410} INFO - Running <TaskInstance: combined_dag.load_modeling scheduled__2023-12-18T13:48:00+00:00 [running]> on host a0e6d5e53f41
[2023-12-18T13:49:57.795+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='combined_dag' AIRFLOW_CTX_TASK_ID='load_modeling' AIRFLOW_CTX_EXECUTION_DATE='2023-12-18T13:48:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-18T13:48:00+00:00'
[2023-12-18T13:49:57.805+0000] {logging_mixin.py:150} INFO - /opt/***
[2023-12-18T13:49:57.805+0000] {combined_dag(real).py:158} INFO - /opt/***
[2023-12-18T13:49:59.457+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"

[2023-12-18T13:49:59.508+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  "X does not have valid feature names, but"

[2023-12-18T13:49:59.878+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but ExtraTreesRegressor was fitted with feature names
  "X does not have valid feature names, but"

[2023-12-18T13:49:59.885+0000] {python.py:183} INFO - Done. Returned value was: (array([26.20186263]), array([3]))
[2023-12-18T13:49:59.907+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=combined_dag, task_id=load_modeling, execution_date=20231218T134800, start_date=20231218T134957, end_date=20231218T134959
[2023-12-18T13:49:59.964+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-12-18T13:49:59.987+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
