[2024-01-03T08:03:02.282+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: modeling_dag.load_modeling scheduled__2024-01-03T08:02:00+00:00 [queued]>
[2024-01-03T08:03:02.289+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: modeling_dag.load_modeling scheduled__2024-01-03T08:02:00+00:00 [queued]>
[2024-01-03T08:03:02.289+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-01-03T08:03:02.300+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_modeling> on 2024-01-03 08:02:00+00:00
[2024-01-03T08:03:02.306+0000] {standard_task_runner.py:57} INFO - Started process 433 to run task
[2024-01-03T08:03:02.309+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'modeling_dag', 'load_modeling', 'scheduled__2024-01-03T08:02:00+00:00', '--job-id', '792', '--raw', '--subdir', 'DAGS_FOLDER/modeling.py', '--cfg-path', '/tmp/tmpxezzui5h']
[2024-01-03T08:03:02.312+0000] {standard_task_runner.py:85} INFO - Job 792: Subtask load_modeling
[2024-01-03T08:03:02.344+0000] {task_command.py:410} INFO - Running <TaskInstance: modeling_dag.load_modeling scheduled__2024-01-03T08:02:00+00:00 [running]> on host c56b1de7f6cf
[2024-01-03T08:03:02.408+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='modeling_dag' AIRFLOW_CTX_TASK_ID='load_modeling' AIRFLOW_CTX_EXECUTION_DATE='2024-01-03T08:02:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-03T08:02:00+00:00'
[2024-01-03T08:03:10.760+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"

[2024-01-03T08:03:10.788+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  "X does not have valid feature names, but"

[2024-01-03T08:03:10.945+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but ExtraTreesRegressor was fitted with feature names
  "X does not have valid feature names, but"

[2024-01-03T08:03:10.962+0000] {python.py:183} INFO - Done. Returned value was: (array([20.91273198]), array([0]))
[2024-01-03T08:03:10.985+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=modeling_dag, task_id=load_modeling, execution_date=20240103T080200, start_date=20240103T080302, end_date=20240103T080310
[2024-01-03T08:03:11.023+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-01-03T08:03:11.041+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
